# Generated by Django 4.0.1 on 2022-02-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_name', models.CharField(max_length=120)),
                ('population', models.PositiveIntegerField()),
                ('first_dosevr', models.PositiveIntegerField()),
                ('second_dosevr', models.PositiveIntegerField()),
            ],
        ),
    ]
