# Generated by Django 4.0.1 on 2022-02-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_orders_address_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
