# Generated by Django 4.0.1 on 2022-03-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
